# Generated by Django 4.2.20 on 2025-05-09 07:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stok', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-olusturma_tarihi'], 'verbose_name': 'Ürün', 'verbose_name_plural': 'Ürünler'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='location',
        ),
        migrations.RemoveField(
            model_name='product',
            name='max_stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='min_stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='product',
            name='aciklama',
            field=models.TextField(blank=True, default='Açıklama girilmedi', null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='product',
            name='adet',
            field=models.IntegerField(default=0, verbose_name='Adet'),
        ),
        migrations.AddField(
            model_name='product',
            name='asgari_adet',
            field=models.IntegerField(default=10, verbose_name='Asgari Adet'),
        ),
        migrations.AddField(
            model_name='product',
            name='birim',
            field=models.CharField(default='Adet', max_length=50, verbose_name='Birim'),
        ),
        migrations.AddField(
            model_name='product',
            name='guncelleme_tarihi',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi'),
        ),
        migrations.AddField(
            model_name='product',
            name='isim',
            field=models.CharField(default='Yeni Ürün', max_length=200, verbose_name='Ürün Adı'),
        ),
        migrations.AddField(
            model_name='product',
            name='marka',
            field=models.CharField(default='Umay', max_length=100, verbose_name='Marka'),
        ),
        migrations.AddField(
            model_name='product',
            name='olusturma_tarihi',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Oluşturma Tarihi'),
        ),
        migrations.AddField(
            model_name='product',
            name='raf_no',
            field=models.CharField(default='A-01', max_length=100, verbose_name='Raf No'),
        ),
        migrations.AddField(
            model_name='product',
            name='urun_kodu',
            field=models.CharField(default='URUN-001', max_length=50, unique=True, verbose_name='Ürün Kodu'),
        ),
    ]
