# Generated by Django 4.2.20 on 2025-05-09 07:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stok', '0002_alter_product_options_remove_product_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-olusturma_tarihi', '-olusturma_saat'], 'verbose_name': 'Ürün', 'verbose_name_plural': 'Ürünler'},
        ),
        migrations.AddField(
            model_name='product',
            name='guncelleme_saat',
            field=models.TimeField(auto_now=True, verbose_name='Güncellenme Saati'),
        ),
        migrations.AddField(
            model_name='product',
            name='olusturma_saat',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Oluşturulma Saati'),
        ),
        migrations.AlterField(
            model_name='product',
            name='birim',
            field=models.CharField(default='Adet', max_length=20, verbose_name='Birim'),
        ),
        migrations.AlterField(
            model_name='product',
            name='guncelleme_tarihi',
            field=models.DateField(auto_now=True, verbose_name='Güncellenme Tarihi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='isim',
            field=models.CharField(default='Yeni Ürün', max_length=100, verbose_name='Ürün Adı'),
        ),
        migrations.AlterField(
            model_name='product',
            name='marka',
            field=models.CharField(default='Umay', max_length=50, verbose_name='Marka'),
        ),
        migrations.AlterField(
            model_name='product',
            name='olusturma_tarihi',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='raf_no',
            field=models.CharField(default='A-01', max_length=20, verbose_name='Raf No'),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_kodu',
            field=models.CharField(default='URUN-001', max_length=50, verbose_name='Ürün Kodu'),
        ),
    ]
