# Generated by Django 4.2.20 on 2025-05-09 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stok', '0003_alter_product_options_product_guncelleme_saat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='olusturma_saat',
            field=models.TimeField(auto_now_add=True, verbose_name='Oluşturulma Saati'),
        ),
        migrations.AlterField(
            model_name='product',
            name='olusturma_tarihi',
            field=models.DateField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
    ]
