# Generated by Django 4.2.20 on 2025-05-09 11:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stok', '0004_alter_product_olusturma_saat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UyariAyarlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uyari_yuzdesi', models.IntegerField(default=20, help_text='Asgari adetin yüzde kaçına düştüğünde sarı uyarı verileceği', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Uyarı Yüzdesi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
            ],
            options={
                'verbose_name': 'Uyarı Ayarı',
                'verbose_name_plural': 'Uyarı Ayarları',
            },
        ),
    ]
