# Generated by Django 4.2.20 on 2025-05-12 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stok', '0005_uyariayarlari'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='muhasebe_kodu',
            field=models.CharField(default='MUH-001', max_length=50, verbose_name='Muhasebe Kodu'),
        ),
    ]
