# Generated by Django 4.2.20 on 2025-05-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stok', '0006_product_muhasebe_kodu'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tedarikci_kodu',
            field=models.CharField(blank=True, help_text='Tedarikçinin ürün için kullandığı kod (opsiyonel)', max_length=50, null=True, verbose_name='Tedarikçi Kodu'),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_kodu',
            field=models.CharField(max_length=50, unique=True, verbose_name='Ürün Kodu'),
        ),
    ]
