# Generated by Django 4.2.20 on 2025-05-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stok', '0007_product_tedarikci_kodu_alter_product_urun_kodu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='aciklama',
            field=models.TextField(blank=True, default='-', null=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='product',
            name='isim',
            field=models.CharField(default='Yeni Ürün', max_length=255, verbose_name='Ürün Adı'),
        ),
        migrations.AlterField(
            model_name='product',
            name='muhasebe_kodu',
            field=models.CharField(default='MUH-001', max_length=50, unique=True, verbose_name='Muhasebe Kodu'),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_kodu',
            field=models.CharField(editable=False, max_length=50, unique=True, verbose_name='Ürün Kodu'),
        ),
    ]
