# Generated by Django 4.2.20 on 2025-05-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stok', '0008_alter_product_aciklama_alter_product_isim_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StokYonetimi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('stok_mobil', 'Stok Mobil Erişimi')],
            },
        ),
    ]
