# Generated by Django 5.2.1 on 2025-05-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stok', '0009_stokyonetimi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-urun_kodu'], 'verbose_name': 'Ürün', 'verbose_name_plural': 'Ürünler'},
        ),
        migrations.AlterModelOptions(
            name='uyariayarlari',
            options={},
        ),
        migrations.RemoveField(
            model_name='product',
            name='aciklama',
        ),
        migrations.RemoveField(
            model_name='product',
            name='guncelleme_saat',
        ),
        migrations.RemoveField(
            model_name='product',
            name='guncelleme_tarihi',
        ),
        migrations.RemoveField(
            model_name='product',
            name='olusturma_saat',
        ),
        migrations.RemoveField(
            model_name='product',
            name='olusturma_tarihi',
        ),
        migrations.RemoveField(
            model_name='uyariayarlari',
            name='guncelleme_tarihi',
        ),
        migrations.AlterField(
            model_name='product',
            name='adet',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='asgari_adet',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='birim',
            field=models.CharField(default='ADET', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='isim',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='marka',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='muhasebe_kodu',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='raf_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='tedarikci_kodu',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_kodu',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='uyariayarlari',
            name='uyari_yuzdesi',
            field=models.IntegerField(default=20),
        ),
    ]
