# Generated by Django 5.2.1 on 2025-05-15 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stok', '0011_alter_product_options_product_guncelleme_tarihi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='aciklama',
            field=models.TextField(blank=True, null=True),
        ),
    ]
