# Generated by Django 5.2.1 on 2025-05-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stok', '0012_product_aciklama'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='guncelleme_saat',
            field=models.TimeField(auto_now=True),
        ),
    ]
