# Generated by Django 4.2.20 on 2025-05-15 08:24

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stok', '0013_product_guncelleme_saat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-olusturma_tarihi', '-olusturma_saat'], 'verbose_name': 'Ürün', 'verbose_name_plural': 'Ürünler'},
        ),
        migrations.AlterModelOptions(
            name='uyariayarlari',
            options={'verbose_name': 'Uyarı Ayarı', 'verbose_name_plural': 'Uyarı Ayarları'},
        ),
        migrations.AddField(
            model_name='product',
            name='olusturma_saat',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Oluşturulma Saati'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uyariayarlari',
            name='guncelleme_tarihi',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='aciklama',
            field=models.TextField(blank=True, default='-', null=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='product',
            name='adet',
            field=models.IntegerField(default=0, verbose_name='Adet'),
        ),
        migrations.AlterField(
            model_name='product',
            name='asgari_adet',
            field=models.IntegerField(default=10, verbose_name='Asgari Adet'),
        ),
        migrations.AlterField(
            model_name='product',
            name='birim',
            field=models.CharField(default='Adet', max_length=20, verbose_name='Birim'),
        ),
        migrations.AlterField(
            model_name='product',
            name='guncelleme_saat',
            field=models.TimeField(auto_now=True, verbose_name='Güncellenme Saati'),
        ),
        migrations.AlterField(
            model_name='product',
            name='guncelleme_tarihi',
            field=models.DateField(auto_now=True, verbose_name='Güncellenme Tarihi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='isim',
            field=models.CharField(default='Yeni Ürün', max_length=255, verbose_name='Ürün Adı'),
        ),
        migrations.AlterField(
            model_name='product',
            name='marka',
            field=models.CharField(default='Umay', max_length=50, verbose_name='Marka'),
        ),
        migrations.AlterField(
            model_name='product',
            name='muhasebe_kodu',
            field=models.CharField(default='MUH-001', max_length=50, unique=True, verbose_name='Muhasebe Kodu'),
        ),
        migrations.AlterField(
            model_name='product',
            name='olusturma_tarihi',
            field=models.DateField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='raf_no',
            field=models.CharField(default='A-01', max_length=20, verbose_name='Raf No'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tedarikci_kodu',
            field=models.CharField(blank=True, help_text='Tedarikçinin ürün için kullandığı kod (opsiyonel)', max_length=50, null=True, verbose_name='Tedarikçi Kodu'),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_kodu',
            field=models.CharField(editable=False, max_length=50, unique=True, verbose_name='Ürün Kodu'),
        ),
        migrations.AlterField(
            model_name='uyariayarlari',
            name='uyari_yuzdesi',
            field=models.IntegerField(default=20, help_text='Asgari adetin yüzde kaçına düştüğünde sarı uyarı verileceği', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Uyarı Yüzdesi'),
        ),
    ]
