# Generated by Django 4.2.20 on 2025-05-16 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stok', '0014_alter_product_options_alter_uyariayarlari_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='birim_fiyati',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Birim Fiyatı'),
        ),
        migrations.AddField(
            model_name='product',
            name='kasa_tipi',
            field=models.CharField(choices=[('normal', 'Normal'), ('ozel', 'Özel'), ('kritik', 'Kritik')], default='normal', max_length=20, verbose_name='Kasa Tipi'),
        ),
        migrations.AddField(
            model_name='product',
            name='urun_tipi',
            field=models.CharField(choices=[('hammadde', 'Hammadde'), ('yarimamul', 'Yarı Mamul'), ('mamul', 'Mamul'), ('sarf', 'Sarf Malzeme')], default='mamul', max_length=20, verbose_name='Ürün Tipi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='olusturma_saat',
            field=models.TimeField(auto_now_add=True, verbose_name='Oluşturma Saati'),
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hareket_tipi', models.CharField(choices=[('giris', 'Giriş'), ('cikis', 'Çıkış')], max_length=10, verbose_name='Hareket Tipi')),
                ('miktar', models.IntegerField(verbose_name='Miktar')),
                ('onceki_stok', models.IntegerField(verbose_name='Önceki Stok')),
                ('sonraki_stok', models.IntegerField(verbose_name='Sonraki Stok')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('islem_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='İşlem Tarihi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='stok.product', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Stok Hareketi',
                'verbose_name_plural': 'Stok Hareketleri',
                'ordering': ['-islem_tarihi'],
            },
        ),
    ]
