# Generated by Django 4.2.20 on 2025-05-16 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stok', '0015_product_birim_fiyati_product_kasa_tipi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='kullanici',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='İşlemi Yapan'),
        ),
    ]
