# Generated by Django 4.2.20 on 2025-05-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stok', '0016_stockmovement_kullanici'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('son_istatistik_sifirlama', models.DateTimeField(blank=True, null=True)),
                ('son_yedekleme', models.DateTimeField(blank=True, null=True)),
                ('sistem_durumu', models.CharField(default='aktif', max_length=20)),
                ('bakim_modu', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
