# Generated by Django 5.2.1 on 2025-05-17 05:49

from django.db import migrations

def update_product_prices(apps, schema_editor):
    Product = apps.get_model('stok', 'Product')
    Product.objects.all().update(birim_fiyati=0)

class Migration(migrations.Migration):

    dependencies = [
        ('stok', '0017_systemsettings'),
    ]

    operations = [
        migrations.RunPython(update_product_prices),
    ]
