# Generated by Django 5.2.1 on 2025-05-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stok', '0018_update_product_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='islem_yapan',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='İşlemi Yapan Kişi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_tipi',
            field=models.CharField(choices=[('hammadde', 'Hammadde'), ('yarimamul', 'Yarı Mamul'), ('mamul', 'Mamul'), ('sarf', 'Sarf Malzeme')], default='sarf', max_length=20, verbose_name='Ürün Tipi'),
        ),
    ]
