# Generated by Django 5.2.1 on 2025-05-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('islem_turu', models.CharField(choices=[('URUN_OLUSTUR', 'Yeni Ürün Oluşturma'), ('URUN_DUZENLE', 'Ürün Düzenleme'), ('UYARI_DUZENLE', 'Uyarı Ayarı Düzenleme'), ('AGAC_OLUSTUR', 'Ağaç Oluşturma'), ('AGAC_DUZENLE', 'Ağaç Düzenleme')], max_length=20)),
                ('kullanici', models.CharField(max_length=150)),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('detay', models.TextField()),
                ('ip_adresi', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Log Kaydı',
                'verbose_name_plural': 'Log Kayıtları',
                'ordering': ['-tarih'],
            },
        ),
    ]
