# Generated by Django 4.2.20 on 2025-05-09 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Kullanıcı Ünvanı', 'verbose_name_plural': 'Kullanıcı Ünvanları'},
        ),
    ]
