# Generated by Django 4.2.20 on 2025-05-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agac', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agac',
            name='id',
        ),
        migrations.AddField(
            model_name='agac',
            name='kod',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
