# Generated by Django 4.2.20 on 2025-05-15 08:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agac', '0002_remove_agac_id_agac_kod'),
    ]

    operations = [
        migrations.AddField(
            model_name='agac',
            name='olusturma_saat',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
