# Generated by Django 4.2.20 on 2025-05-15 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agac', '0003_agac_olusturma_saat'),
    ]

    operations = [
        migrations.AddField(
            model_name='agac',
            name='son_guncelleyen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guncelleyen_agaclar', to=settings.AUTH_USER_MODEL),
        ),
    ]
