# Generated by Django 4.2.20 on 2025-05-15 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agac', '0004_agac_son_guncelleyen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agac',
            name='olusturan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='olusturan_agaclar', to=settings.AUTH_USER_MODEL),
        ),
    ]
